const CURRENCIES = {
    AED: { symbol: 'د.إ', name: 'UAE Dirham' },
    AFN: { symbol: '؋', name: 'Afghan Afghani' },
    ALL: { symbol: 'L', name: 'Albanian Lek' },
    AMD: { symbol: '֏', name: 'Armenian Dram' },
    ANG: { symbol: 'ƒ', name: 'Netherlands Antillean Guilder' },
    AOA: { symbol: 'Kz', name: 'Angolan Kwanza' },
    ARS: { symbol: '$', name: 'Argentine Peso' },
    AUD: { symbol: 'A$', name: 'Australian Dollar' },
    AWG: { symbol: 'ƒ', name: 'Aruban Florin' },
    AZN: { symbol: '₼', name: 'Azerbaijani Manat' },
    BAM: { symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark' },
    BBD: { symbol: '$', name: 'Barbadian Dollar' },
    BDT: { symbol: '৳', name: 'Bangladeshi Taka' },
    BGN: { symbol: 'лв', name: 'Bulgarian Lev' },
    BHD: { symbol: '.د.ب', name: 'Bahraini Dinar' },
    BIF: { symbol: 'FBu', name: 'Burundian Franc' },
    BMD: { symbol: '$', name: 'Bermudian Dollar' },
    BND: { symbol: '$', name: 'Brunei Dollar' },
    BOB: { symbol: 'Bs.', name: 'Bolivian Boliviano' },
    BRL: { symbol: 'R$', name: 'Brazilian Real' },
    BSD: { symbol: '$', name: 'Bahamian Dollar' },
    BTN: { symbol: 'Nu.', name: 'Bhutanese Ngultrum' },
    BWP: { symbol: 'P', name: 'Botswana Pula' },
    BYN: { symbol: 'Br', name: 'Belarusian Ruble' },
    BZD: { symbol: 'BZ$', name: 'Belize Dollar' },
    CAD: { symbol: 'C$', name: 'Canadian Dollar' },
    CDF: { symbol: 'FC', name: 'Congolese Franc' },
    CHF: { symbol: 'Fr.', name: 'Swiss Franc' },
    CLP: { symbol: '$', name: 'Chilean Peso' },
    CNY: { symbol: '¥', name: 'Chinese Yuan' },
    COP: { symbol: '$', name: 'Colombian Peso' },
    CRC: { symbol: '₡', name: 'Costa Rican Colon' },
    CUP: { symbol: '$', name: 'Cuban Peso' },
    CVE: { symbol: '$', name: 'Cape Verdean Escudo' },
    CZK: { symbol: 'Kč', name: 'Czech Koruna' },
    DJF: { symbol: 'Fdj', name: 'Djiboutian Franc' },
    DKK: { symbol: 'kr', name: 'Danish Krone' },
    DOP: { symbol: 'RD$', name: 'Dominican Peso' },
    DZD: { symbol: 'د.ج', name: 'Algerian Dinar' },
    EGP: { symbol: 'E£', name: 'Egyptian Pound' },
    ERN: { symbol: 'Nfk', name: 'Eritrean Nakfa' },
    ETB: { symbol: 'Br', name: 'Ethiopian Birr' },
    EUR: { symbol: '€', name: 'Euro' },
    FJD: { symbol: '$', name: 'Fijian Dollar' },
    FKP: { symbol: '£', name: 'Falkland Islands Pound' },
    GBP: { symbol: '£', name: 'British Pound' },
    GEL: { symbol: '₾', name: 'Georgian Lari' },
    GHS: { symbol: '₵', name: 'Ghanaian Cedi' },
    GIP: { symbol: '£', name: 'Gibraltar Pound' },
    GMD: { symbol: 'D', name: 'Gambian Dalasi' },
    GNF: { symbol: 'FG', name: 'Guinean Franc' },
    GTQ: { symbol: 'Q', name: 'Guatemalan Quetzal' },
    GYD: { symbol: '$', name: 'Guyanese Dollar' },
    HKD: { symbol: 'HK$', name: 'Hong Kong Dollar' },
    HNL: { symbol: 'L', name: 'Honduran Lempira' },
    HTG: { symbol: 'G', name: 'Haitian Gourde' },
    HUF: { symbol: 'Ft', name: 'Hungarian Forint' },
    IDR: { symbol: 'Rp', name: 'Indonesian Rupiah' },
    ILS: { symbol: '₪', name: 'Israeli New Shekel' },
    INR: { symbol: '₹', name: 'Indian Rupee' },
    IQD: { symbol: 'ع.د', name: 'Iraqi Dinar' },
    IRR: { symbol: '﷼', name: 'Iranian Rial' },
    ISK: { symbol: 'kr', name: 'Icelandic Krona' },
    JMD: { symbol: 'J$', name: 'Jamaican Dollar' },
    JOD: { symbol: 'د.ا', name: 'Jordanian Dinar' },
    JPY: { symbol: '¥', name: 'Japanese Yen' },
    KES: { symbol: 'KSh', name: 'Kenyan Shilling' },
    KGS: { symbol: 'с', name: 'Kyrgyzstani Som' },
    KHR: { symbol: '៛', name: 'Cambodian Riel' },
    KMF: { symbol: 'CF', name: 'Comorian Franc' },
    KPW: { symbol: '₩', name: 'North Korean Won' },
    KRW: { symbol: '₩', name: 'South Korean Won' },
    KWD: { symbol: 'د.ك', name: 'Kuwaiti Dinar' },
    KYD: { symbol: '$', name: 'Cayman Islands Dollar' },
    KZT: { symbol: '₸', name: 'Kazakhstani Tenge' },
    LAK: { symbol: '₭', name: 'Lao Kip' },
    LBP: { symbol: 'ل.ل', name: 'Lebanese Pound' },
    LKR: { symbol: 'Rs', name: 'Sri Lankan Rupee' },
    LRD: { symbol: '$', name: 'Liberian Dollar' },
    LSL: { symbol: 'L', name: 'Lesotho Loti' },
    LYD: { symbol: 'ل.د', name: 'Libyan Dinar' },
    MAD: { symbol: 'د.م.', name: 'Moroccan Dirham' },
    MDL: { symbol: 'L', name: 'Moldovan Leu' },
    MGA: { symbol: 'Ar', name: 'Malagasy Ariary' },
    MKD: { symbol: 'ден', name: 'Macedonian Denar' },
    MMK: { symbol: 'K', name: 'Myanmar Kyat' },
    MNT: { symbol: '₮', name: 'Mongolian Tugrik' },
    MOP: { symbol: 'MOP$', name: 'Macanese Pataca' },
    MRU: { symbol: 'UM', name: 'Mauritanian Ouguiya' },
    MUR: { symbol: '₨', name: 'Mauritian Rupee' },
    MVR: { symbol: 'Rf', name: 'Maldivian Rufiyaa' },
    MWK: { symbol: 'MK', name: 'Malawian Kwacha' },
    MXN: { symbol: '$', name: 'Mexican Peso' },
    MYR: { symbol: 'RM', name: 'Malaysian Ringgit' },
    MZN: { symbol: 'MT', name: 'Mozambican Metical' },
    NAD: { symbol: '$', name: 'Namibian Dollar' },
    NGN: { symbol: '₦', name: 'Nigerian Naira' },
    NIO: { symbol: 'C$', name: 'Nicaraguan Cordoba' },
    NOK: { symbol: 'kr', name: 'Norwegian Krone' },
    NPR: { symbol: '₨', name: 'Nepalese Rupee' },
    NZD: { symbol: 'NZ$', name: 'New Zealand Dollar' },
    OMR: { symbol: 'ر.ع.', name: 'Omani Rial' },
    PAB: { symbol: 'B/.', name: 'Panamanian Balboa' },
    PEN: { symbol: 'S/', name: 'Peruvian Sol' },
    PGK: { symbol: 'K', name: 'Papua New Guinean Kina' },
    PHP: { symbol: '₱', name: 'Philippine Peso' },
    PKR: { symbol: '₨', name: 'Pakistani Rupee' },
    PLN: { symbol: 'zł', name: 'Polish Zloty' },
    PYG: { symbol: '₲', name: 'Paraguayan Guarani' },
    QAR: { symbol: 'ر.ق', name: 'Qatari Riyal' },
    RON: { symbol: 'lei', name: 'Romanian Leu' },
    RSD: { symbol: 'дин.', name: 'Serbian Dinar' },
    RUB: { symbol: '₽', name: 'Russian Ruble' },
    RWF: { symbol: 'FRw', name: 'Rwandan Franc' },
    SAR: { symbol: 'ر.س', name: 'Saudi Riyal' },
    SBD: { symbol: '$', name: 'Solomon Islands Dollar' },
    SCR: { symbol: '₨', name: 'Seychellois Rupee' },
    SDG: { symbol: 'ج.س.', name: 'Sudanese Pound' },
    SEK: { symbol: 'kr', name: 'Swedish Krona' },
    SGD: { symbol: 'S$', name: 'Singapore Dollar' },
    SHP: { symbol: '£', name: 'Saint Helena Pound' },
    SLE: { symbol: 'Le', name: 'Sierra Leonean Leone' },
    SOS: { symbol: 'Sh', name: 'Somali Shilling' },
    SRD: { symbol: '$', name: 'Surinamese Dollar' },
    SSP: { symbol: '£', name: 'South Sudanese Pound' },
    STN: { symbol: 'Db', name: 'Sao Tome and Principe Dobra' },
    SYP: { symbol: '£S', name: 'Syrian Pound' },
    SZL: { symbol: 'L', name: 'Swazi Lilangeni' },
    THB: { symbol: '฿', name: 'Thai Baht' },
    TJS: { symbol: 'ЅМ', name: 'Tajikistani Somoni' },
    TMT: { symbol: 'm', name: 'Turkmenistani Manat' },
    TND: { symbol: 'د.ت', name: 'Tunisian Dinar' },
    TOP: { symbol: 'T$', name: 'Tongan Paanga' },
    TRY: { symbol: '₺', name: 'Turkish Lira' },
    TTD: { symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
    TWD: { symbol: 'NT$', name: 'New Taiwan Dollar' },
    TZS: { symbol: 'TSh', name: 'Tanzanian Shilling' },
    UAH: { symbol: '₴', name: 'Ukrainian Hryvnia' },
    UGX: { symbol: 'USh', name: 'Ugandan Shilling' },
    USD: { symbol: '$', name: 'US Dollar' },
    UYU: { symbol: '$U', name: 'Uruguayan Peso' },
    UZS: { symbol: "so'm", name: 'Uzbekistani Som' },
    VES: { symbol: 'Bs.', name: 'Venezuelan Bolivar' },
    VND: { symbol: '₫', name: 'Vietnamese Dong' },
    VUV: { symbol: 'VT', name: 'Vanuatu Vatu' },
    WST: { symbol: 'WS$', name: 'Samoan Tala' },
    XAF: { symbol: 'FCFA', name: 'Central African CFA Franc' },
    XCD: { symbol: '$', name: 'East Caribbean Dollar' },
    XOF: { symbol: 'CFA', name: 'West African CFA Franc' },
    XPF: { symbol: '₣', name: 'CFP Franc' },
    YER: { symbol: '﷼', name: 'Yemeni Rial' },
    ZAR: { symbol: 'R', name: 'South African Rand' },
    ZMW: { symbol: 'ZK', name: 'Zambian Kwacha' },
    ZWL: { symbol: '$', name: 'Zimbabwean Dollar' },
};

const COUNTRY_CURRENCY = {
    AD: 'EUR',
    AE: 'AED',
    AF: 'AFN',
    AG: 'XCD',
    AI: 'XCD',
    AL: 'ALL',
    AM: 'AMD',
    AO: 'AOA',
    AQ: 'USD',
    AR: 'ARS',
    AS: 'USD',
    AT: 'EUR',
    AU: 'AUD',
    AW: 'AWG',
    AX: 'EUR',
    AZ: 'AZN',
    BA: 'BAM',
    BB: 'BBD',
    BD: 'BDT',
    BE: 'EUR',
    BF: 'XOF',
    BG: 'EUR',
    BH: 'BHD',
    BI: 'BIF',
    BJ: 'XOF',
    BL: 'EUR',
    BM: 'BMD',
    BN: 'BND',
    BO: 'BOB',
    BQ: 'USD',
    BR: 'BRL',
    BS: 'BSD',
    BT: 'BTN',
    BV: 'NOK',
    BW: 'BWP',
    BY: 'BYN',
    BZ: 'BZD',
    CA: 'CAD',
    CC: 'AUD',
    CD: 'CDF',
    CF: 'XAF',
    CG: 'XAF',
    CH: 'CHF',
    CI: 'XOF',
    CK: 'NZD',
    CL: 'CLP',
    CM: 'XAF',
    CN: 'CNY',
    CO: 'COP',
    CR: 'CRC',
    CU: 'CUP',
    CV: 'CVE',
    CW: 'ANG',
    CX: 'AUD',
    CY: 'EUR',
    CZ: 'CZK',
    DE: 'EUR',
    DJ: 'DJF',
    DK: 'DKK',
    DM: 'XCD',
    DO: 'DOP',
    DZ: 'DZD',
    EC: 'USD',
    EE: 'EUR',
    EG: 'EGP',
    EH: 'MAD',
    ER: 'ERN',
    ES: 'EUR',
    ET: 'ETB',
    FI: 'EUR',
    FJ: 'FJD',
    FK: 'FKP',
    FM: 'USD',
    FO: 'DKK',
    FR: 'EUR',
    GA: 'XAF',
    GB: 'GBP',
    GD: 'XCD',
    GE: 'GEL',
    GF: 'EUR',
    GG: 'GBP',
    GH: 'GHS',
    GI: 'GIP',
    GL: 'DKK',
    GM: 'GMD',
    GN: 'GNF',
    GP: 'EUR',
    GQ: 'XAF',
    GR: 'EUR',
    GS: 'GBP',
    GT: 'GTQ',
    GU: 'USD',
    GW: 'XOF',
    GY: 'GYD',
    HK: 'HKD',
    HM: 'AUD',
    HN: 'HNL',
    HR: 'EUR',
    HT: 'HTG',
    HU: 'HUF',
    ID: 'IDR',
    IE: 'EUR',
    IL: 'ILS',
    IM: 'GBP',
    IN: 'INR',
    IO: 'USD',
    IQ: 'IQD',
    IR: 'IRR',
    IS: 'ISK',
    IT: 'EUR',
    JE: 'GBP',
    JM: 'JMD',
    JO: 'JOD',
    JP: 'JPY',
    KE: 'KES',
    KG: 'KGS',
    KH: 'KHR',
    KI: 'AUD',
    KM: 'KMF',
    KN: 'XCD',
    KP: 'KPW',
    KR: 'KRW',
    KW: 'KWD',
    KY: 'KYD',
    KZ: 'KZT',
    LA: 'LAK',
    LB: 'LBP',
    LC: 'XCD',
    LI: 'CHF',
    LK: 'LKR',
    LR: 'LRD',
    LS: 'LSL',
    LT: 'EUR',
    LU: 'EUR',
    LV: 'EUR',
    LY: 'LYD',
    MA: 'MAD',
    MC: 'EUR',
    MD: 'MDL',
    ME: 'EUR',
    MF: 'EUR',
    MG: 'MGA',
    MH: 'USD',
    MK: 'MKD',
    ML: 'XOF',
    MM: 'MMK',
    MN: 'MNT',
    MO: 'MOP',
    MP: 'USD',
    MQ: 'EUR',
    MR: 'MRU',
    MS: 'XCD',
    MT: 'EUR',
    MU: 'MUR',
    MV: 'MVR',
    MW: 'MWK',
    MX: 'MXN',
    MY: 'MYR',
    MZ: 'MZN',
    NA: 'NAD',
    NC: 'XPF',
    NE: 'XOF',
    NF: 'AUD',
    NG: 'NGN',
    NI: 'NIO',
    NL: 'EUR',
    NO: 'NOK',
    NP: 'NPR',
    NR: 'AUD',
    NU: 'NZD',
    NZ: 'NZD',
    OM: 'OMR',
    PA: 'PAB',
    PE: 'PEN',
    PF: 'XPF',
    PG: 'PGK',
    PH: 'PHP',
    PK: 'PKR',
    PL: 'PLN',
    PM: 'EUR',
    PN: 'NZD',
    PR: 'USD',
    PS: 'ILS',
    PT: 'EUR',
    PW: 'USD',
    PY: 'PYG',
    QA: 'QAR',
    RE: 'EUR',
    RO: 'RON',
    RS: 'RSD',
    RU: 'RUB',
    RW: 'RWF',
    SA: 'SAR',
    SB: 'SBD',
    SC: 'SCR',
    SD: 'SDG',
    SE: 'SEK',
    SG: 'SGD',
    SH: 'SHP',
    SI: 'EUR',
    SJ: 'NOK',
    SK: 'EUR',
    SL: 'SLE',
    SM: 'EUR',
    SN: 'XOF',
    SO: 'SOS',
    SR: 'SRD',
    SS: 'SSP',
    ST: 'STN',
    SV: 'USD',
    SX: 'ANG',
    SY: 'SYP',
    SZ: 'SZL',
    TC: 'USD',
    TD: 'XAF',
    TF: 'EUR',
    TG: 'XOF',
    TH: 'THB',
    TJ: 'TJS',
    TK: 'NZD',
    TL: 'USD',
    TM: 'TMT',
    TN: 'TND',
    TO: 'TOP',
    TR: 'TRY',
    TT: 'TTD',
    TV: 'AUD',
    TW: 'TWD',
    TZ: 'TZS',
    UA: 'UAH',
    UG: 'UGX',
    UM: 'USD',
    US: 'USD',
    UY: 'UYU',
    UZ: 'UZS',
    VA: 'EUR',
    VC: 'XCD',
    VE: 'VES',
    VG: 'USD',
    VI: 'USD',
    VN: 'VND',
    VU: 'VUV',
    WF: 'XPF',
    WS: 'WST',
    XK: 'EUR',
    YE: 'YER',
    YT: 'EUR',
    ZA: 'ZAR',
    ZM: 'ZMW',
    ZW: 'ZWL',
};

const DEFAULT_COUNTRY = 'IN';

function getCurrencyByCountry(countryCode) {
    const normalizedCountry = String(countryCode || '').toUpperCase();
    const currencyCode = COUNTRY_CURRENCY[normalizedCountry] || COUNTRY_CURRENCY[DEFAULT_COUNTRY];
    const currency = CURRENCIES[currencyCode] || CURRENCIES.INR;

    return {
        currency: currencyCode,
        symbol: currency.symbol,
        name: currency.name,
    };
}

function getCurrencySymbolByCurrency(currencyCode) {
    const currency = CURRENCIES[currencyCode] || CURRENCIES.INR;
    return currency.symbol;
}

const FLAG_COUNTRY = {
    INR: '🇮🇳',
    AED: '🇦🇪',
    USD: '🇺🇸',
    GBP: '🇬🇧',
    CAD: '🇨🇦',
    SAR: '🇸🇦',
    QAR: '🇶🇦',
    SGD: '🇸🇬',
    AUD: '🇦🇺',
    EUR: '🇪🇺',
    MYR: '🇲🇾',
    ZAR: '🇿🇦',
    FJD: '🇫🇯',
    MUR: '🇲🇺',
    PHP: '🇵🇭',
    BRL: '🇧🇷',
    MXN: '🇲🇽',
}

function getCurrencyIconByCurrency(currencyCode) {
    const currency = FLAG_COUNTRY[currencyCode] || FLAG_COUNTRY.INR;
    console.log("currency", currency);
    return currency;
}

module.exports = {
    CURRENCIES,
    COUNTRY_CURRENCY,
    getCurrencyByCountry,
    getCurrencySymbolByCurrency,
    getCurrencyIconByCurrency
};
