const CURRENCIES = {
    AED: { symbol: 'AED', name: 'UAE Dirham' },
    AFN: { symbol: 'AFN', name: 'Afghan Afghani' },
    ALL: { symbol: 'ALL', name: 'Albanian Lek' },
    AMD: { symbol: 'AMD', name: 'Armenian Dram' },
    ANG: { symbol: 'ANG', name: 'Netherlands Antillean Guilder' },
    AOA: { symbol: 'AOA', name: 'Angolan Kwanza' },
    ARS: { symbol: 'ARS', name: 'Argentine Peso' },
    AUD: { symbol: 'A$', name: 'Australian Dollar' },
    AWG: { symbol: 'AWG', name: 'Aruban Florin' },
    AZN: { symbol: 'AZN', name: 'Azerbaijani Manat' },
    BAM: { symbol: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark' },
    BBD: { symbol: 'BBD', name: 'Barbadian Dollar' },
    BDT: { symbol: 'BDT', name: 'Bangladeshi Taka' },
    BGN: { symbol: 'BGN', name: 'Bulgarian Lev' },
    BHD: { symbol: 'BHD', name: 'Bahraini Dinar' },
    BIF: { symbol: 'BIF', name: 'Burundian Franc' },
    BMD: { symbol: 'BMD', name: 'Bermudian Dollar' },
    BND: { symbol: 'BND', name: 'Brunei Dollar' },
    BOB: { symbol: 'BOB', name: 'Bolivian Boliviano' },
    BRL: { symbol: 'R$', name: 'Brazilian Real' },
    BSD: { symbol: 'BSD', name: 'Bahamian Dollar' },
    BTN: { symbol: 'BTN', name: 'Bhutanese Ngultrum' },
    BWP: { symbol: 'BWP', name: 'Botswana Pula' },
    BYN: { symbol: 'BYN', name: 'Belarusian Ruble' },
    BZD: { symbol: 'BZD', name: 'Belize Dollar' },
    CAD: { symbol: 'C$', name: 'Canadian Dollar' },
    CDF: { symbol: 'CDF', name: 'Congolese Franc' },
    CHF: { symbol: 'CHF', name: 'Swiss Franc' },
    CLP: { symbol: 'CLP', name: 'Chilean Peso' },
    CNY: { symbol: 'CNY', name: 'Chinese Yuan' },
    COP: { symbol: 'COP', name: 'Colombian Peso' },
    CRC: { symbol: 'CRC', name: 'Costa Rican Colon' },
    CUP: { symbol: 'CUP', name: 'Cuban Peso' },
    CVE: { symbol: 'CVE', name: 'Cape Verdean Escudo' },
    CZK: { symbol: 'CZK', name: 'Czech Koruna' },
    DJF: { symbol: 'DJF', name: 'Djiboutian Franc' },
    DKK: { symbol: 'DKK', name: 'Danish Krone' },
    DOP: { symbol: 'DOP', name: 'Dominican Peso' },
    DZD: { symbol: 'DZD', name: 'Algerian Dinar' },
    EGP: { symbol: 'EGP', name: 'Egyptian Pound' },
    ERN: { symbol: 'ERN', name: 'Eritrean Nakfa' },
    ETB: { symbol: 'ETB', name: 'Ethiopian Birr' },
    EUR: { symbol: 'EUR', name: 'Euro' },
    FJD: { symbol: 'FJD', name: 'Fijian Dollar' },
    FKP: { symbol: 'FKP', name: 'Falkland Islands Pound' },
    GBP: { symbol: 'GBP', name: 'British Pound' },
    GEL: { symbol: 'GEL', name: 'Georgian Lari' },
    GHS: { symbol: 'GHS', name: 'Ghanaian Cedi' },
    GIP: { symbol: 'GIP', name: 'Gibraltar Pound' },
    GMD: { symbol: 'GMD', name: 'Gambian Dalasi' },
    GNF: { symbol: 'GNF', name: 'Guinean Franc' },
    GTQ: { symbol: 'GTQ', name: 'Guatemalan Quetzal' },
    GYD: { symbol: 'GYD', name: 'Guyanese Dollar' },
    HKD: { symbol: 'HKD', name: 'Hong Kong Dollar' },
    HNL: { symbol: 'HNL', name: 'Honduran Lempira' },
    HTG: { symbol: 'HTG', name: 'Haitian Gourde' },
    HUF: { symbol: 'HUF', name: 'Hungarian Forint' },
    IDR: { symbol: 'IDR', name: 'Indonesian Rupiah' },
    ILS: { symbol: 'ILS', name: 'Israeli New Shekel' },
    INR: { symbol: 'Rs', name: 'Indian Rupee' },
    IQD: { symbol: 'IQD', name: 'Iraqi Dinar' },
    IRR: { symbol: 'IRR', name: 'Iranian Rial' },
    ISK: { symbol: 'ISK', name: 'Icelandic Krona' },
    JMD: { symbol: 'JMD', name: 'Jamaican Dollar' },
    JOD: { symbol: 'JOD', name: 'Jordanian Dinar' },
    JPY: { symbol: 'JPY', name: 'Japanese Yen' },
    KES: { symbol: 'KES', name: 'Kenyan Shilling' },
    KGS: { symbol: 'KGS', name: 'Kyrgyzstani Som' },
    KHR: { symbol: 'KHR', name: 'Cambodian Riel' },
    KMF: { symbol: 'KMF', name: 'Comorian Franc' },
    KPW: { symbol: 'KPW', name: 'North Korean Won' },
    KRW: { symbol: 'KRW', name: 'South Korean Won' },
    KWD: { symbol: 'KWD', name: 'Kuwaiti Dinar' },
    KYD: { symbol: 'KYD', name: 'Cayman Islands Dollar' },
    KZT: { symbol: 'KZT', name: 'Kazakhstani Tenge' },
    LAK: { symbol: 'LAK', name: 'Lao Kip' },
    LBP: { symbol: 'LBP', name: 'Lebanese Pound' },
    LKR: { symbol: 'LKR', name: 'Sri Lankan Rupee' },
    LRD: { symbol: 'LRD', name: 'Liberian Dollar' },
    LSL: { symbol: 'LSL', name: 'Lesotho Loti' },
    LYD: { symbol: 'LYD', name: 'Libyan Dinar' },
    MAD: { symbol: 'MAD', name: 'Moroccan Dirham' },
    MDL: { symbol: 'MDL', name: 'Moldovan Leu' },
    MGA: { symbol: 'MGA', name: 'Malagasy Ariary' },
    MKD: { symbol: 'MKD', name: 'Macedonian Denar' },
    MMK: { symbol: 'MMK', name: 'Myanmar Kyat' },
    MNT: { symbol: 'MNT', name: 'Mongolian Tugrik' },
    MOP: { symbol: 'MOP', name: 'Macanese Pataca' },
    MRU: { symbol: 'MRU', name: 'Mauritanian Ouguiya' },
    MUR: { symbol: 'MUR', name: 'Mauritian Rupee' },
    MVR: { symbol: 'MVR', name: 'Maldivian Rufiyaa' },
    MWK: { symbol: 'MWK', name: 'Malawian Kwacha' },
    MXN: { symbol: 'MXN', name: 'Mexican Peso' },
    MYR: { symbol: 'MYR', name: 'Malaysian Ringgit' },
    MZN: { symbol: 'MZN', name: 'Mozambican Metical' },
    NAD: { symbol: 'NAD', name: 'Namibian Dollar' },
    NGN: { symbol: 'NGN', name: 'Nigerian Naira' },
    NIO: { symbol: 'NIO', name: 'Nicaraguan Cordoba' },
    NOK: { symbol: 'NOK', name: 'Norwegian Krone' },
    NPR: { symbol: 'NPR', name: 'Nepalese Rupee' },
    NZD: { symbol: 'NZD', name: 'New Zealand Dollar' },
    OMR: { symbol: 'OMR', name: 'Omani Rial' },
    PAB: { symbol: 'PAB', name: 'Panamanian Balboa' },
    PEN: { symbol: 'PEN', name: 'Peruvian Sol' },
    PGK: { symbol: 'PGK', name: 'Papua New Guinean Kina' },
    PHP: { symbol: 'PHP', name: 'Philippine Peso' },
    PKR: { symbol: 'PKR', name: 'Pakistani Rupee' },
    PLN: { symbol: 'PLN', name: 'Polish Zloty' },
    PYG: { symbol: 'PYG', name: 'Paraguayan Guarani' },
    QAR: { symbol: 'QAR', name: 'Qatari Riyal' },
    RON: { symbol: 'RON', name: 'Romanian Leu' },
    RSD: { symbol: 'RSD', name: 'Serbian Dinar' },
    RUB: { symbol: 'RUB', name: 'Russian Ruble' },
    RWF: { symbol: 'RWF', name: 'Rwandan Franc' },
    SAR: { symbol: 'SAR', name: 'Saudi Riyal' },
    SBD: { symbol: 'SBD', name: 'Solomon Islands Dollar' },
    SCR: { symbol: 'SCR', name: 'Seychellois Rupee' },
    SDG: { symbol: 'SDG', name: 'Sudanese Pound' },
    SEK: { symbol: 'SEK', name: 'Swedish Krona' },
    SGD: { symbol: 'SGD', name: 'Singapore Dollar' },
    SHP: { symbol: 'SHP', name: 'Saint Helena Pound' },
    SLE: { symbol: 'SLE', name: 'Sierra Leonean Leone' },
    SOS: { symbol: 'SOS', name: 'Somali Shilling' },
    SRD: { symbol: 'SRD', name: 'Surinamese Dollar' },
    SSP: { symbol: 'SSP', name: 'South Sudanese Pound' },
    STN: { symbol: 'STN', name: 'Sao Tome and Principe Dobra' },
    SYP: { symbol: 'SYP', name: 'Syrian Pound' },
    SZL: { symbol: 'SZL', name: 'Swazi Lilangeni' },
    THB: { symbol: 'THB', name: 'Thai Baht' },
    TJS: { symbol: 'TJS', name: 'Tajikistani Somoni' },
    TMT: { symbol: 'TMT', name: 'Turkmenistani Manat' },
    TND: { symbol: 'TND', name: 'Tunisian Dinar' },
    TOP: { symbol: 'TOP', name: 'Tongan Paanga' },
    TRY: { symbol: 'TRY', name: 'Turkish Lira' },
    TTD: { symbol: 'TTD', name: 'Trinidad and Tobago Dollar' },
    TWD: { symbol: 'TWD', name: 'New Taiwan Dollar' },
    TZS: { symbol: 'TZS', name: 'Tanzanian Shilling' },
    UAH: { symbol: 'UAH', name: 'Ukrainian Hryvnia' },
    UGX: { symbol: 'UGX', name: 'Ugandan Shilling' },
    USD: { symbol: 'USD', name: 'US Dollar' },
    UYU: { symbol: 'UYU', name: 'Uruguayan Peso' },
    UZS: { symbol: 'UZS', name: 'Uzbekistani Som' },
    VES: { symbol: 'VES', name: 'Venezuelan Bolivar' },
    VND: { symbol: 'VND', name: 'Vietnamese Dong' },
    VUV: { symbol: 'VUV', name: 'Vanuatu Vatu' },
    WST: { symbol: 'WST', name: 'Samoan Tala' },
    XAF: { symbol: 'XAF', name: 'Central African CFA Franc' },
    XCD: { symbol: 'XCD', name: 'East Caribbean Dollar' },
    XOF: { symbol: 'XOF', name: 'West African CFA Franc' },
    XPF: { symbol: 'XPF', name: 'CFP Franc' },
    YER: { symbol: 'YER', name: 'Yemeni Rial' },
    ZAR: { symbol: 'ZAR', name: 'South African Rand' },
    ZMW: { symbol: 'ZMW', name: 'Zambian Kwacha' },
    ZWL: { symbol: 'ZWL', name: 'Zimbabwean Dollar' },
};

const COUNTRY_CURRENCY = {
    AD: 'EUR',
    AE: 'AED',
    AF: 'AFN',
    AG: 'XCD',
    AI: 'XCD',
    AL: 'ALL',
    AM: 'AMD',
    AO: 'AOA',
    AQ: 'USD',
    AR: 'ARS',
    AS: 'USD',
    AT: 'EUR',
    AU: 'AUD',
    AW: 'AWG',
    AX: 'EUR',
    AZ: 'AZN',
    BA: 'BAM',
    BB: 'BBD',
    BD: 'BDT',
    BE: 'EUR',
    BF: 'XOF',
    BG: 'EUR',
    BH: 'BHD',
    BI: 'BIF',
    BJ: 'XOF',
    BL: 'EUR',
    BM: 'BMD',
    BN: 'BND',
    BO: 'BOB',
    BQ: 'USD',
    BR: 'BRL',
    BS: 'BSD',
    BT: 'BTN',
    BV: 'NOK',
    BW: 'BWP',
    BY: 'BYN',
    BZ: 'BZD',
    CA: 'CAD',
    CC: 'AUD',
    CD: 'CDF',
    CF: 'XAF',
    CG: 'XAF',
    CH: 'CHF',
    CI: 'XOF',
    CK: 'NZD',
    CL: 'CLP',
    CM: 'XAF',
    CN: 'CNY',
    CO: 'COP',
    CR: 'CRC',
    CU: 'CUP',
    CV: 'CVE',
    CW: 'ANG',
    CX: 'AUD',
    CY: 'EUR',
    CZ: 'CZK',
    DE: 'EUR',
    DJ: 'DJF',
    DK: 'DKK',
    DM: 'XCD',
    DO: 'DOP',
    DZ: 'DZD',
    EC: 'USD',
    EE: 'EUR',
    EG: 'EGP',
    EH: 'MAD',
    ER: 'ERN',
    ES: 'EUR',
    ET: 'ETB',
    FI: 'EUR',
    FJ: 'FJD',
    FK: 'FKP',
    FM: 'USD',
    FO: 'DKK',
    FR: 'EUR',
    GA: 'XAF',
    GB: 'GBP',
    GD: 'XCD',
    GE: 'GEL',
    GF: 'EUR',
    GG: 'GBP',
    GH: 'GHS',
    GI: 'GIP',
    GL: 'DKK',
    GM: 'GMD',
    GN: 'GNF',
    GP: 'EUR',
    GQ: 'XAF',
    GR: 'EUR',
    GS: 'GBP',
    GT: 'GTQ',
    GU: 'USD',
    GW: 'XOF',
    GY: 'GYD',
    HK: 'HKD',
    HM: 'AUD',
    HN: 'HNL',
    HR: 'EUR',
    HT: 'HTG',
    HU: 'HUF',
    ID: 'IDR',
    IE: 'EUR',
    IL: 'ILS',
    IM: 'GBP',
    IN: 'INR',
    IO: 'USD',
    IQ: 'IQD',
    IR: 'IRR',
    IS: 'ISK',
    IT: 'EUR',
    JE: 'GBP',
    JM: 'JMD',
    JO: 'JOD',
    JP: 'JPY',
    KE: 'KES',
    KG: 'KGS',
    KH: 'KHR',
    KI: 'AUD',
    KM: 'KMF',
    KN: 'XCD',
    KP: 'KPW',
    KR: 'KRW',
    KW: 'KWD',
    KY: 'KYD',
    KZ: 'KZT',
    LA: 'LAK',
    LB: 'LBP',
    LC: 'XCD',
    LI: 'CHF',
    LK: 'LKR',
    LR: 'LRD',
    LS: 'LSL',
    LT: 'EUR',
    LU: 'EUR',
    LV: 'EUR',
    LY: 'LYD',
    MA: 'MAD',
    MC: 'EUR',
    MD: 'MDL',
    ME: 'EUR',
    MF: 'EUR',
    MG: 'MGA',
    MH: 'USD',
    MK: 'MKD',
    ML: 'XOF',
    MM: 'MMK',
    MN: 'MNT',
    MO: 'MOP',
    MP: 'USD',
    MQ: 'EUR',
    MR: 'MRU',
    MS: 'XCD',
    MT: 'EUR',
    MU: 'MUR',
    MV: 'MVR',
    MW: 'MWK',
    MX: 'MXN',
    MY: 'MYR',
    MZ: 'MZN',
    NA: 'NAD',
    NC: 'XPF',
    NE: 'XOF',
    NF: 'AUD',
    NG: 'NGN',
    NI: 'NIO',
    NL: 'EUR',
    NO: 'NOK',
    NP: 'NPR',
    NR: 'AUD',
    NU: 'NZD',
    NZ: 'NZD',
    OM: 'OMR',
    PA: 'PAB',
    PE: 'PEN',
    PF: 'XPF',
    PG: 'PGK',
    PH: 'PHP',
    PK: 'PKR',
    PL: 'PLN',
    PM: 'EUR',
    PN: 'NZD',
    PR: 'USD',
    PS: 'ILS',
    PT: 'EUR',
    PW: 'USD',
    PY: 'PYG',
    QA: 'QAR',
    RE: 'EUR',
    RO: 'RON',
    RS: 'RSD',
    RU: 'RUB',
    RW: 'RWF',
    SA: 'SAR',
    SB: 'SBD',
    SC: 'SCR',
    SD: 'SDG',
    SE: 'SEK',
    SG: 'SGD',
    SH: 'SHP',
    SI: 'EUR',
    SJ: 'NOK',
    SK: 'EUR',
    SL: 'SLE',
    SM: 'EUR',
    SN: 'XOF',
    SO: 'SOS',
    SR: 'SRD',
    SS: 'SSP',
    ST: 'STN',
    SV: 'USD',
    SX: 'ANG',
    SY: 'SYP',
    SZ: 'SZL',
    TC: 'USD',
    TD: 'XAF',
    TF: 'EUR',
    TG: 'XOF',
    TH: 'THB',
    TJ: 'TJS',
    TK: 'NZD',
    TL: 'USD',
    TM: 'TMT',
    TN: 'TND',
    TO: 'TOP',
    TR: 'TRY',
    TT: 'TTD',
    TV: 'AUD',
    TW: 'TWD',
    TZ: 'TZS',
    UA: 'UAH',
    UG: 'UGX',
    UM: 'USD',
    US: 'USD',
    UY: 'UYU',
    UZ: 'UZS',
    VA: 'EUR',
    VC: 'XCD',
    VE: 'VES',
    VG: 'USD',
    VI: 'USD',
    VN: 'VND',
    VU: 'VUV',
    WF: 'XPF',
    WS: 'WST',
    XK: 'EUR',
    YE: 'YER',
    YT: 'EUR',
    ZA: 'ZAR',
    ZM: 'ZMW',
    ZW: 'ZWL',
};

const DEFAULT_COUNTRY = 'IN';

function getCurrencyByCountry(countryCode) {
    const normalizedCountry = String(countryCode || '').toUpperCase();
    const currencyCode = COUNTRY_CURRENCY[normalizedCountry] || COUNTRY_CURRENCY[DEFAULT_COUNTRY];
    const currency = CURRENCIES[currencyCode] || CURRENCIES.INR;

    return {
        currency: currencyCode,
        symbol: currency.symbol,
        name: currency.name,
    };
}

module.exports = {
    CURRENCIES,
    COUNTRY_CURRENCY,
    getCurrencyByCountry,
};
